### ISSUE TITLE
Certain doutbts regarding the tracking module

### ISSUE THREAD

**Issue by chakri1804** [ShenhanQian/VHAP#1]
Hi,
Thanks for sharing this amazing repo

I have a couple of questions
1. Does matting cause a significant difference in tracking accuracy vs no matting images ?
2. Is there a flag to track non-matted images ? Or do we have to matt the images and then pass a certain flag to force it to not use alpha images
3. I see that in the final track, we have the hair shape tracked as well. 
Does this mean the flame shape itself is modified based on the person's hair style ?
If yes, is there a way to disable that part and track like normal metrical tracker ?
4. The pytorch3drenderer.py is missing from the utils folder. Can I just use the file from GaussianAvatars repo to substitute it ?
5. If I track with nvdiffraster and try using the fl and camera params with pytorch3d camera, would it work ?
6. I think the camera being used for all rendering is a Perspective Camera in pytorch3d. But the camera params are not being saved in the final params.npz file (except for the focal length). Is there a simple calculation I can do to get the camera params for pytorch3d (R,T, fl, pp or RT, K, etc) ?
7. Is any sort of filtering being applied before rendering the overlay video or is it just the raw results from the tracker ?

**Comment by ShenhanQian** [comment]
Hi, thanks for your questions!

1. Matting is not always necessary. It mainly helps prevent artifacts when the background color is too close to any part of the foreground.
2. Yes, you can pass `--data.background_color None` to avoid loading alpha maps during tracking.
3. We add `static_offset`, which is a per-vertice offset in the canonical space of FLAME. It does not change the topology of the mesh. You can easily disable it with `--model.no_use_static_offset`
4. The pytorch3d renderer is deprecated for our repository. Since the algorithm of NVDiffRast is fundamentally different from PyTorch3D, simply moving to PyTorch3D rasterizer may produce very different results.
5. It should work if you use PyTorch3D just for visualization instead of optimization. The major difference is the camera convention.
6. We don't have a direct reference for you to conduct this conversion. The following could be useful:
https://github.com/ShenhanQian/GaussianAvatars/blob/f1d772fcbbce7d3765b8d7e1470b7c24fe6d85f6/reference_tracker/mvht/util/render_pytorch3d.py#L12-L35
7. No. The parameters are visualized as they are. They look smooth because we apply temporal smoothness losses. But you may want to adjust the loss weights according to your needs.

**Comment by chakri1804** [comment]
Thanks for the clear reply
I use a piece of code which renders the meshes given flame params and camera params. Then it overlays it on top of the original image. Hence the question regarding the Pytorch3D conversion. From the blob you've shared, it just seems to be a matter of calculating RT and K similar to how its being done inside the nvdiffrast code. So for this case, the camera param conversion should be fine
