### ISSUE TITLE
How to use Pytorch3D to render the flame mesh of NeRSemble dataset? 

### ISSUE THREAD

**Issue by Zazexy** [ShenhanQian/VHAP#15]
Hello, thanks for your great work!
I saw that there is a abandon pytorch3d renderer in your project which is mentioned in `tracker.py` line 76. 
I saw that you use `rast_dict = self.render.rasterize(verts, faces, RT, K, image_size, False, train_mode)` to call the customized pytorch3d render.
I wanna know how to process the extrinsic and intrinsic provided by NeRSemble's camera params file or Pytorch3d renderer to make both work together to rasterize the pixel-correct picture from the FLAME mesh.
I couldn't use nvdiffrast since my environment base WSL2, which doesn't support nvdiffrast yet. So I want to use pytorch3d as mesh renderer for NeRSemble dataset.

**Comment by ShenhanQian** [comment]
Hi, thanks for your question. We would not encourge you to switch to PyTorch3D because its mechanism to compute visibility gradient is foundamentally different from nvdiffrast, therefore will not give you good results. 

For Windows, you could try the native windows environment with Visual studio instead of inside nvdiffrast. We provide some instructions for setting up the environment on Windows for GaussianAvatar [here](https://github.com/ShenhanQian/GaussianAvatars/blob/main/doc/installation.md#for-windows-with-powershell). The same procedure should also work for VHAP.

**Comment by Zazexy** [comment]
Thank you for your response!

**Comment by ShenhanQian** [comment]
Given an upgrade of nvdiffrast, VHAP now runs entirely based on CUDA. Therefore, you should be able to run it inside WSL2.
Please pull the lastest commit and upgrade nvdiffrast as instructed here:
https://github.com/ShenhanQian/VHAP/releases/tag/v0.0.2
