### ISSUE TITLE
Questions about cropping the video

### ISSUE THREAD

**Issue by HaoZhiG** [ShenhanQian/VHAP#8]
Thanks for release! I was wondering if you have considered cropping only the neck to head portion from the NeRSemble dataset, without including the shoulders?

**Comment by ShenhanQian** [comment]
It's possible to do so with predicted semantic masks. But these masks are not always robust and depend on the shape of the collars. Therefore, we fit a line, which is almost consistent across views and subjects, and mask out the region below.

Meanwhile, if we raise the line to higher positions, such as the neck, we may accidentally crop our the jaw in side views.

**Comment by vipinsdk** [comment]
Hello Shenhan, 

Is it recommended to run the pipeline without cropping the videos to the shoulder region. I am asking this because the camera intrinsics are computed on the actual video size and if we cut the video then the intrinsics will also change right?
If we were to hypothetically detect the shoulder region and fit a line, is this recommended?

Thanks in advance. 

With regards,
Vippin

**Comment by ShenhanQian** [comment]
Hi Vippin, our cropping only happens during export after tracking. You do not need to modify the video nor the camera intrinsics.
