### ISSUE TITLE
Evaluate performance of FLAME 2020 vs 2023 in VHAP and GaussianAvatars

### ISSUE THREAD

**Issue by Jp-17** [ShenhanQian/VHAP#9]
Currently, both VHAP (Video-based Human Avatar Personalization) and GaussianAvatars utilize the FLAME 2023 version by default. I'm curious about the potential implications of using the FLAME 2020 version instead:

Would switching to FLAME 2020 result in any noticeable degradation in the quality of avatars generated by GaussianAvatars? Are there any specific advantages or disadvantages to using FLAME 2020 versus 2023 in this context?

Any insights, experiences, or suggestions would be greatly appreciated. Thank you!

**Comment by ShenhanQian** [comment]
Hi, I also had the same question before but have not got an answer: https://github.com/TimoBolkart/FLAME-Universe/discussions/4

Based on my previous experiments, there wasn't a huge difference, but FLAME 2023 allowed me to get slightly better results for eyelids.

**Comment by Jp-17** [comment]
Thank you for your response, and sorry for reply late. I have conducted some further experiments with different conditions and have a few additional questions:

In the uploaded video_1 （ https://github.com/user-attachments/assets/5747e0d0-a03f-423d-a06e-75bca86ac836 ）, I want to use FLAME parameters obtained from a different method (not VHAP) to drive the already trained GaussianAvatars (this method produces FLAME 2020 parameters, so for compatibility, when driving the model trained with FLAME 2023, I have already matched the versions of FLAME parameters in flame.py).

1. When using FLAME parameters obtained from the method other than VHAP to drive the trained GaussianAvatars model, I noticed that the 2020 version resulted in less pronounced teeth movement compared to the 2023 version (as seen in the video 2020 vs 2023 under the same conditions).

2. Although VHAP downsamples the video to 1/4 resolution, I expected that training GaussianAvatars with full-resolution video would result in a better mesh-bound 3DGS model. However, my results don't show a significant improvement in 3DGS quality (as seen in the video comparison of TrainDS1 vs TrainDS4).

3. I anticipated that using spherical harmonics parameter sh=3 during GaussianAvatars training would yield better 3DGS results compared to sh=0. However, my comparisons show that sh=0 actually has fewer transparency issues in novel view angles, particularly noticeable between the eyes and nose and on the upper lip (as seen in the first row sh=3 vs second row sh=0 in the video).

By the way, the rendering videos using flame got by VHAP on nersemble sen-01 videos (which i use for trainin) all look the same quality, which is not inflluenced by the different parameter combination (seen the video_2 https://github.com/user-attachments/assets/42830d5b-2359-4a8e-9da1-3c71e7c3a7f7 )

 Could you explain this unexpected outcome? I would greatly appreciate your thoughts on these observations. Thank you for your time and expertise!

**Comment by ShenhanQian** [comment]
Hi, thanks for sharing your results.

If I understand correctly, you trained GaussianAvatars with NeRSemble sequences tracked with VHAP and reenacted the avatar with novel FLAME poses and expressions obtained from some other tracker. Then you found the results were not as good as expected and tried several variations to improve them.

For your questions,
1. The difference in mouths is a bit subtle to me. You may have gotten this impression from more examples. But I'm glad to know your discovery.

2. With DS-1, I can indeed observe better details such as sharper ear edges and more precise eyeball texture. However, the rendering is still not satisfying because of the gap between the training and test data. For Video 1, the camera is viewing from a higher position, revealing artifacts that could be fixed by 1) more training views, poses, and expressions; 2) depth/opacity regularizations.

3. Same as above. A higher degree of SH enhances the model's ability to fit the training data but can also produce more artifacts with unseen viewing angles, poses, and expressions. You may get some improvement by computing a relative transformation to align the FLAME poses for inference to the training ones.

**Comment by Jp-17** [comment]
Wow, Thank you, you've understood my questions very well.

1. I should have included comparison images. The issue with FLAME 2020 vs 2023 in video-1 is specifically in the teeth area inside the mouth (see Figure 1).
<img width="613" alt="aa93506efd0f0c5206217578bd8839a" src="https://github.com/user-attachments/assets/5b0e8ba1-da46-49a1-a06e-4e4b11b22da6">

2-1. Thank you for your observation. Indeed, you're right that the eyes and ears look better in DS1; I hadn't noticed that before. I'd like to ask a follow-up question: Should we aim for even higher resolution data collection and training, such as 4K? Based on these results, I'm concerned that the improvements from increased resolution might not be as significant as imagined.

2-2. Thank you for your suggestion about generalization from training to inference. Could you please elaborate more on your ideas regarding depth and opacity regularization? How to understand "depth" here?

3. About the SH issuse, I understand your point, thank you!

Thank you for your time and expertise!

**Comment by ShenhanQian** [comment]
Hi, 

1. Thanks for the examples. They make the differences quite obvious.
2-1. I think it depends on your method. GaussianAvatars's dynamic capacity is limited by the number of triangles. Currently, several splats are rigidly bound to each triangle. Supervising with larger images will bind more splats onto each mesh, but since sharing motion between too many splats is inaccurate, you won't get super-sharp results. As a remedy, you can use a network to learn conditional mapping from expressions to per-splat motion. Then, you will need to use enough data to make sure the network generalizes well to novel expressions.
2-2. The current artifacts are due to the existence of holes and semi-transparent splats. The problem can be relieved if you can 
1) regularize the depth to be close to the FLAME mesh for the facial region;
2) push splats to fully opaque or transparent instead of semi-transparent.

**Comment by Jp-17** [comment]
Your explanation is very clear, thank you so much!

Regarding 2-1, theoretically, would it also be possible to use a non-FLAME mesh model, for example, training our own mesh model with more triangles, and using a VAE to learn latent parameters z to control this mesh's deformation? This way, we could bind more splats to the mesh.

**Comment by ShenhanQian** [comment]
Theoretically, yes. However, it can take some effort to reach a robustness similar to FLAME. Although we can always increase the resolution, whether the additional details should be generalizable across identities or personalized becomes an interesting question.

**Comment by Jp-17** [comment]
Got it. Thank you for your patient reply!
